# workflow name 
name: build and test the app 

# when the workflow will be triggered 
on: 
  push: 
    branches: 
      - main 

# where will the workflow run 
jobs: 
  run_unit_tests: 
    runs-on: ubuntu-latest 
    steps: 
     # checkout repository 
      - name: Checkout 
        uses: actions/checkout@v2.4.0 

   # install java  
      - name: Setup JDK 
        uses: actions/setup-java@v2.4.0 
        with: 
          distribution: 'zulu' 
          java-version: '8' 

   # use gradle commands 
      - name: Setup Gradle 
        uses: gradle/gradle-build-action@v2 
